'use client';
import {useState,useEffect,useRef,createContext,useContext,type ReactNode} from 'react';
import {Compass,ArrowRight,ShieldCheck,LogOut,Cloud,AlertCircle} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {parseSave,type Save} from './game';
export type Account={user:{id:string;name:string;role:'student'|'teacher'};save:Save;revision:number;serverTime:string};
export async function api(path:string,body?:unknown,method='POST'):Promise<any>{const response=await fetch(path,{method:body===undefined?'GET':method,headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),credentials:'same-origin'});let value:any;try{value=await response.json()}catch{throw Error('接続できませんでした。インターネット接続を確認してください。')}if(!response.ok)throw Error(value.error||'処理できませんでした');return value}
const Context=createContext<{account:Account;logout:()=>Promise<void>;refresh:()=>Promise<void>}|null>(null);
export function useAccount(){const c=useContext(Context);if(!c)throw Error('Login required');return c}
export function AccountGate({children}:{children:ReactNode}){const [account,setAccount]=useState<Account|null>(null);const [loading,setLoading]=useState(true);const [mode,setMode]=useState('login');const [name,setName]=useState('');const [password,setPassword]=useState('');const [repeat,setRepeat]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
async function refresh(){const data=await api('/api/account');if(data.user){setAccount({...data,save:parseSave(data.save)})}else setAccount(null)}
useEffect(()=>{refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
async function logout(){await api('/api/account',{action:'logout'});setAccount(null);setPassword('');setRepeat('');setMode('login')}
async function submit(e:React.FormEvent){e.preventDefault();setError('');if(mode==='register'&&password!==repeat){setError('パスワードが一致していません');return}setBusy(true);try{await api('/api/account',{action:mode,name,password});await refresh();setPassword('');setRepeat('')}catch(e){setError(e instanceof Error?e.message:'ログインできませんでした')}finally{setBusy(false)}}
if(account)return <Context.Provider value={{account,logout,refresh}}><div key={account.user.id}>{children}</div></Context.Provider>;
return <main className="login-page"><img className="login-art" src="/world-map.png" alt="冒険の島々"/><div className="login-vignette"/><div className="login-brand"><Compass/><span>SCRATCH <b>QUEST</b></span></div><section className="login-card"><p className="eyebrow">YOUR ADVENTURE AWAITS</p><h1>{mode==='teacher'?'先生の部屋へ':mode==='register'?'きみの冒険の書をつくろう。':'おかえり、冒険者。'}</h1><p>{mode==='teacher'?'先生用のパスワードで入ってください。':'同じパソコンでも、別のパソコンでも。きみの続きから、はじめよう。'}</p>{loading?<p role="status" className="connection-status">冒険の書を確認しています…</p>:<><Tabs value={mode==='teacher'?'login':mode} onValueChange={v=>{setMode(String(v));setError('');setPassword('');setRepeat('')}}><TabsList className="login-tabs" aria-label="ログインか新規登録"><TabsTrigger value="login">ログイン</TabsTrigger><TabsTrigger value="register">はじめての登録</TabsTrigger></TabsList></Tabs><form onSubmit={submit}>{mode!=='teacher'&&<label>なまえ<input autoComplete="username" value={name} onChange={e=>setName(e.target.value)} maxLength={20} required placeholder="登録したなまえ"/></label>}<label>パスワード<input type="password" autoComplete={mode==='register'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} minLength={6} maxLength={128} required placeholder={mode==='teacher'?'先生用のパスワード':'6文字以上'}/></label>{mode==='register'&&<label>もう一度、パスワード<input type="password" autoComplete="new-password" value={repeat} onChange={e=>setRepeat(e.target.value)} minLength={6} required/></label>}{error&&<p className="error-text" role="alert"><AlertCircle size={16}/>{error}</p>}<button className="gold-button" disabled={busy}>{busy?'確認しています…':mode==='register'?'登録して冒険をはじめる':mode==='teacher'?'先生の部屋をひらく':'冒険のつづきへ'}<ArrowRight size={18}/></button></form><button className="teacher-entry" onClick={()=>{setMode(mode==='teacher'?'login':'teacher');setPassword('');setError('')}}><ShieldCheck size={16}/>{mode==='teacher'?'生徒のログインにもどる':'先生はこちら'}</button></>}<p className="login-note"><Cloud size={16}/>記録はアカウントに保存されます</p></section></main>}
export function useCloudSave(save:Save){const {account}=useAccount();const [status,setStatus]=useState('保存済み');const revision=useRef(account.revision);const committed=useRef(JSON.stringify(account.save));const latest=useRef(save);latest.current=save;const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const flight=useRef<Promise<void>|null>(null);const blocked=useRef(false);const [error,setError]=useState('');
async function flush(){if(account.user.role==='teacher'||blocked.current)return;while(flight.current)await flight.current;const serialized=JSON.stringify(latest.current);if(serialized===committed.current)return;setStatus('保存中…');const job=(async()=>{try{const r=await api('/api/progress',{save:JSON.parse(serialized),revision:revision.current},'PUT');revision.current=r.revision;committed.current=serialized;setStatus('保存済み');setError('')}catch(e){const message=e instanceof Error?e.message:'保存できませんでした';setError(message);setStatus('未保存');if(/別の画面|ログイン|更新され/.test(message))blocked.current=true;throw e}})();flight.current=job;try{await job}finally{flight.current=null}}
useEffect(()=>{if(account.user.role==='teacher')return;if(JSON.stringify(save)===committed.current)return;setStatus('保存待ち');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{flush().catch(()=>{})},500);return()=>{if(timer.current)clearTimeout(timer.current)}},[save]);
useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(JSON.stringify(latest.current)!==committed.current&&account.user.role==='student'){e.preventDefault();e.returnValue=''}};const retry=()=>flush().catch(()=>{});window.addEventListener('beforeunload',warn);window.addEventListener('online',retry);return()=>{window.removeEventListener('beforeunload',warn);window.removeEventListener('online',retry)}},[]);
return {status,error,flush};}
export function LogoutButton({flush}:{flush:()=>Promise<void>}){const {logout}=useAccount();const [busy,setBusy]=useState(false);const [error,setError]=useState('');return <div><button className="subtle" disabled={busy} onClick={async()=>{setBusy(true);try{await flush();await logout()}catch(e){setError(e instanceof Error?e.message:'ログアウトできませんでした')}finally{setBusy(false)}}}><LogOut size={16}/>{busy?'記録を保存中…':'ログアウト'}</button>{error&&<p className="error-text">{error}</p>}</div>}
