'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,SkipForward,BookOpen,ChevronLeft} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type CourseId,courses} from './game';
type Scene={speaker:'rio'|'algo'|'mira'|'narrator';text:string;place?:'map'|'lab';choice?:boolean};
const names={rio:'リオ',algo:'アルゴ',mira:'ミラ博士',narrator:'物語'};
const basicIntro:Scene[]=[{speaker:'narrator',text:'ここは、プログラムで動く不思議な王国。ところがある朝、広場に魔物が現れた。',place:'map'},{speaker:'rio',text:'来てくれたんだね！ ぼくはリオ。となりの猫はビット。きみの冒険の案内役だよ。'},{speaker:'algo',text:'ピピッ！ 勇者のプログラムを確認。……移動の命令が、見つかりません！'},{speaker:'rio',text:'勇者は助けに行きたいのに、一歩も動けないんだ。きみの力を貸してくれる？',choice:true},{speaker:'mira',text:'私はミラ。プログラムの研究をしているの。大丈夫、最初に必要なのは、たったひとつの命令よ。',place:'lab'},{speaker:'algo',text:'「右に動いて」って伝えられたら……勇者が歩けるかも！'},{speaker:'rio',text:'そう。Scratchのブロックは、思いつきをキャラクターに伝える道具なんだ。',place:'map'},{speaker:'rio',text:'最初のミッションは「勇者を動かせ！」。矢印キーを押したら、その方向へ進む仕組みを作ろう。'}];
const advanceIntro:Scene[]=[{speaker:'narrator',text:'星の海に浮かぶ、クリエイターズ・アカデミー。今日、ひとりの新しい開発者がやってきた。',place:'map'},{speaker:'mira',text:'ようこそ。開発チームへ！ 私はミラ。最初の依頼を、一緒に確認しましょう。',place:'lab'},{speaker:'algo',text:'緊急報告！ テスト中のゲームが、おかしな動きをしています！'},{speaker:'rio',text:'見た目は完成しているのに、遊んでみると変なんだ。きみなら最初に、何をする？',choice:true},{speaker:'mira',text:'そうね。いきなり全部を書き換える前に、「何をしたら、何が起こるか」を確かめましょう。'},{speaker:'algo',text:'ぼくはテスト係！ 同じ手順で、もう一度バグが起きるか調べます。'},{speaker:'rio',text:'原因をひとつに絞って直し、ほかの動きも確かめる。チームでゲームを完成させよう！'},{speaker:'mira',text:'最初の依頼は「症状を書きだせ」。観察したことが、修理への最初の手がかりよ。'}];
export default function Novel({cid,chapter,onStart}:{cid:CourseId;chapter:number;onStart:()=>void}){const ch=courses[cid==='basic'?0:1].chapters[chapter];const scenes:Scene[]=chapter===0?(cid==='basic'?basicIntro:advanceIntro):ch.story.map((text,i)=>({speaker:i===0?'narrator':cid==='advance'?(i%2?'mira':'algo'):(i%2?'rio':'algo'),text,place:cid==='advance'||chapter===1?'lab':'map'}));const [step,setStep]=useState(0);const [count,setCount]=useState(0);const [reply,setReply]=useState('');const [history,setHistory]=useState(false);const [chosen,setChosen]=useState(false);const scene=scenes[step];const text=reply||scene.text;const full=count>=text.length;const location=scene.place||[...scenes.slice(0,step+1)].reverse().find(x=>x.place)?.place||'map';
useEffect(()=>{setCount(0);if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setCount(text.length);return}const timer=setInterval(()=>setCount(n=>{if(n>=text.length){clearInterval(timer);return n}return n+1}),24);return()=>clearInterval(timer)},[text]);
function next(){if(!full){setCount(text.length);return}if(scene.choice&&!chosen)return;if(step===scenes.length-1){onStart();return}setStep(s=>s+1);setReply('');setChosen(false)}
function choose(index:number){setChosen(true);setReply(cid==='basic'?(index===0?'リオ「ありがとう！ まず、きみが動かしたい方向を思い浮かべてみよう。」':'ミラ「もちろん。勇者にひとつずつ命令を伝えればいいの。一緒に試しましょう。」'):(index===0?'ミラ「いい視点ね。同じ手順で何度起きるか確かめて、症状を記録しましょう。」':'リオ「動くはずの姿を考えるんだね。実際の動きとの違いを書きだしてみよう。」'))}
return <section className={'novel-stage '+cid} tabIndex={0} aria-label="物語。Enterまたはスペースで会話を進めます" onKeyDown={e=>{if(e.target===e.currentTarget&&['Enter',' '].includes(e.key)){e.preventDefault();next()}}}><img key={location} className="novel-background" src={location==='lab'?'/academy-lab.png':cid==='basic'?'/world-map.png':'/advance-map.png'} alt={location==='lab'?'星空を望む研究室':ch.world}/><div className="novel-shade"/><header className="novel-top"><div><span className="eyebrow">CHAPTER {String(chapter+1).padStart(2,'0')} · {ch.month}</span><h1>{ch.title}</h1></div><div className="novel-controls"><button onClick={()=>setHistory(true)}><BookOpen size={15}/>会話ログ</button><button onClick={onStart}><SkipForward size={15}/>ミッションへ</button></div></header><div className="novel-cast" aria-hidden="true"><div className={'cast-person rio '+(scene.speaker==='rio'?'speaking':'')}><img src="/adventurer.png" alt=""/></div><div className={'cast-person algo '+(scene.speaker==='algo'?'speaking':'')}/><div className={'cast-person mira '+(scene.speaker==='mira'?'speaking':'')}/></div><div className="novel-dialog"><div className="speaker-tag">{names[scene.speaker]} <span>{scene.speaker==='narrator'?'PROLOGUE':'◆'}</span></div><button className="novel-text" onClick={()=>{if(!full)setCount(text.length);else if(!scene.choice||chosen)next()}} aria-label={text}><span aria-hidden="true">{text.slice(0,count)}<i className="text-cursor"/></span></button>{scene.choice&&full&&!chosen&&<div className="novel-choices">{(cid==='basic'?['勇者を動かしてみたい！','もう少し、教えてほしい']:['同じ操作で症状を確かめる','期待した動きと比べる']).map((label,i)=><button onClick={()=>choose(i)} key={label}>{label}<ArrowRight size={15}/></button>)}</div>}<div className="novel-footer"><button disabled={step===0} onClick={()=>{setStep(s=>s-1);setReply('');setChosen(false)}}><ChevronLeft size={16}/>前の会話</button><span>{step+1} / {scenes.length}</span><button className="gold-button" disabled={!!scene.choice&&!chosen&&full} onClick={next}>{!full?'全文を表示':step===scenes.length-1?'クエストに出発':'つぎへ'}<ArrowRight size={17}/></button></div></div><Dialog open={history} onOpenChange={setHistory}><DialogContent className="novel-log"><DialogTitle>これまでの会話</DialogTitle><DialogDescription>この章の物語を読み返せます。</DialogDescription>{scenes.slice(0,step+1).map((s,i)=><p key={i}><strong>{names[s.speaker]}</strong>{s.text}</p>)}{reply&&<p>{reply}</p>}</DialogContent></Dialog></section>}
