'use client';
import {AccountGate,useAccount,useCloudSave,LogoutButton} from './accounts';
import Teacher from './teacher';
import Workshop from './workshop';
import {ChapterFiles,ChapterSubmit} from './resources';
import Novel from './novel';
import {availableChapters,japanCalendar} from './game';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {flushSync} from 'react-dom';
import {Map,BookOpen,Trophy,UserRound,Settings,Palette,Sparkles,ArrowRight,ArrowLeft,Lock,Compass,Swords,Flag,Check,ExternalLink,Lightbulb,ChevronRight,Download,Upload,RotateCcw,Star,Rocket,Medal} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Progress} from '@/components/ui/progress';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {courses,specialAwards,freshSave,parseSave,progress,cleared,unlocked,firstChapter,totalMissions,markMission,safeUrl,places,outcome,SAVE_KEY,type Save,type CourseId} from './game';
type View='studio'|'map'|'quests'|'chapter'|'mission'|'awards'|'profile'|'settings';
const navigation=[{id:'map',icon:Map,label:'冒険マップ'},{id:'quests',icon:BookOpen,label:'クエスト'},{id:'studio',icon:Palette,label:'自由制作'},{id:'awards',icon:Trophy,label:'宝もの図鑑'},{id:'profile',icon:UserRound,label:'ぼうけんの記録'}] as const;
const titles:Record<View,string>={studio:'自由制作',map:'冒険マップ',quests:'クエスト',chapter:'物語',mission:'ミッション',awards:'宝もの図鑑',profile:'ぼうけんの記録',settings:'教室の設定'};
function Navigation({view,go}:{view:View;go:(v:View)=>void}){const {setOpenMobile}=useSidebar();return <SidebarMenu>{navigation.map(({id,icon:Icon,label})=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id||(id==='quests'&&['chapter','mission'].includes(view))} className="nav-item" onClick={()=>{go(id);setOpenMobile(false)}}><Icon/>{label}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>}
export default function Page(){return <AccountGate><Home/></AccountGate>}
function Home(){
const {account}=useAccount();const isTeacher=account.user.role==='teacher';
const [save,setSave]=useState<Save>(()=>account.save);const [loaded,setLoaded]=useState(true);const [view,setView]=useState<View>(isTeacher?'settings':'map');const [selected,setSelected]=useState(()=>totalMissions(account.save)?firstChapter(account.save,account.save.course):Math.max(0,availableChapters(account.save)-1));const [mi,setMi]=useState(0);const [storyStep,setStoryStep]=useState(0);const [hints,setHints]=useState(0);const [answer,setAnswer]=useState(false);const [checked,setChecked]=useState(false);const [celebration,setCelebration]=useState<{chapter:boolean;text:string}|null>(null);const [notice,setNotice]=useState('');const [confirm,setConfirm]=useState<'reset'|'import'|'undo'|null>(null);const [pendingImport,setPendingImport]=useState<Save|null>(null);const [special,setSpecial]=useState(specialAwards[0].id);const fileRef=useRef<HTMLInputElement>(null);const stateRef=useRef(save);stateRef.current=save;
const cid=save.course;const course=courses[cid==='basic'?0:1];const ch=course.chapters[selected];const cp=progress(save,cid,selected);const mission=ch.missions[mi];const current=firstChapter(save,cid);const total=totalMissions(save);const level=Math.floor(total/3)+1;const chapterCount=course.chapters.filter((_,i)=>cleared(save,cid,i)).length;const allClear=chapterCount===12;const doneCount=cp.missions.filter(Boolean).length;const canOpen=unlocked(save,cid,selected);const guide=cid==='basic'?'旅の仲間 リオ & ビット':'開発パートナー リオ & ビット';
const cloud=useCloudSave(save);
const [,refreshCalendar]=useState(0);useEffect(()=>{const update=()=>refreshCalendar(n=>n+1);const timer=setInterval(update,60000);window.addEventListener('focus',update);return()=>{clearInterval(timer);window.removeEventListener('focus',update)}},[]);
function go(v:View){setView(v);setNotice('');window.scrollTo({top:0,behavior:'instant'})}
function switchCourse(value:CourseId){setSave(s=>({...s,course:value}));setSelected(firstChapter(save,value));setStoryStep(0);go('map')}
function openChapter(i:number){if(!unlocked(save,cid,i)){setSelected(i);go('map');return}setSelected(i);setStoryStep(0);go('chapter')}
function openMission(i:number){setMi(i);setHints(0);setAnswer(false);setChecked(false);setSave(s=>({...s,last:{course:cid,chapter:selected,mission:i}}));go('mission')}
function complete(){if(!checked||cp.missions[mi])return;const next=markMission(save,cid,selected,mi);setSave(next);setCelebration({chapter:cleared(next,cid,selected),text:outcome(cid,selected,mi)})}
function afterCelebration(){const finished=celebration?.chapter;setCelebration(null);if(finished){setSelected(firstChapter(save,cid));go('map')}else{const next=cp.missions.findIndex(x=>!x);openMission(next<0?0:next)}}
function exportSave(){const blob=new Blob([JSON.stringify(save,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='scratch-quest-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function importFile(file?:File){if(!file)return;try{if(file.size>1000000)throw Error('記録ファイルが大きすぎます');setPendingImport({...parseSave(JSON.parse(await file.text())),name:save.name,startYear:save.startYear,opts:save.opts,special:save.special});setConfirm('import')}catch(e){setNotice(e instanceof Error?e.message:'読みこめませんでした')}if(fileRef.current)fileRef.current.value=''}
function confirmed(){if(confirm==='reset'){setSave(freshSave());setSelected(0);go('map')}if(confirm==='import'&&pendingImport){setSave(pendingImport);setSelected(firstChapter(pendingImport,pendingImport.course));setPendingImport(null);go('map')}if(confirm==='undo')setSave(markMission(save,cid,selected,mi,false));setConfirm(null)}
useEffect(()=>{type Tool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(x:unknown)=>unknown};const context=(document as Document&{modelContext?:{registerTool:(t:Tool,o:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context)return;const ac=new AbortController();const tools:Tool[]=[{name:'read_scratch_quest_progress',description:'Read saved Scratch Quest progress for both courses on this device.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({course:stateRef.current.course,completedMissions:totalMissions(stateRef.current),progress:stateRef.current.progress})},{name:'open_scratch_quest_chapter',description:'Open an unlocked chapter story. Does not mark any learning completed.',inputSchema:{type:'object',properties:{course:{type:'string',enum:['basic','advance']},chapter:{type:'integer',minimum:1,maximum:12}},required:['course','chapter'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input)=>{if(!input||typeof input!=='object')throw Error('Invalid input');const x=input as {course:CourseId;chapter:number};if(!['basic','advance'].includes(x.course)||!Number.isInteger(x.chapter)||x.chapter<1||x.chapter>12)throw Error('Invalid chapter');if(!unlocked(stateRef.current,x.course,x.chapter-1))throw Error('Chapter locked');flushSync(()=>{setSave(s=>({...s,course:x.course}));setSelected(x.chapter-1);setStoryStep(0);setView('chapter')});return {course:x.course,chapter:x.chapter,view:'chapter'}}}];for(const t of tools){try{Promise.resolve(context.registerTool(t,{signal:ac.signal})).catch(()=>{})}catch{}}return()=>ac.abort()},[]);
const mapImage=cid==='basic'?'/world-map.png':'/advance-map.png';
const crop=selected===0?'18% 22%':selected===1?'85% 20%':`${places[selected][0]}% ${places[selected][1]}%`;
return <SidebarProvider style={{'--sidebar-width':'238px'} as CSSProperties} className={cid==='advance'?'advance':''}><Sidebar><SidebarHeader><button className="brand" onClick={()=>go('map')} aria-label="冒険マップへ"><Compass/><span>SCRATCH<br/><b>QUEST</b></span></button><div className="course-label">{course.bookTitle}<span>{course.name}</span></div></SidebarHeader><SidebarContent><p className="nav-label">{cid==='basic'?'ADVENTURE':'CREATOR JOURNEY'}</p><Navigation view={view} go={go}/><div className="companion"><img src="/adventurer.png" alt="案内役リオと猫のビット"/><strong>{allClear?'すべての世界を冒険したね！':'準備はいい？'}</strong><p>きみのプログラムで、<br/>この世界を動かそう。</p></div></SidebarContent><SidebarFooter><button className="subtle" onClick={()=>go('settings')}><Settings size={17}/>{isTeacher?'先生の部屋':'記録の管理'}</button><LogoutButton flush={cloud.flush}/><span className="cloud-status" role="status">{isTeacher?'先生としてログイン中':cloud.status}</span><small>SCRATCH QUEST • ぼうけんの書</small></SidebarFooter></Sidebar><main className="main"><header className="topline"><div><SidebarTrigger aria-label="メニューを開く"/><span>{course.bookTitle}</span><span className="divider">/</span><b>{titles[view]}</b></div><button className="player" onClick={()=>go('profile')}><Sparkles size={17}/><b>Lv. {level}</b><span>{save.name||'はじまりの冒険者'}</span><img src="/adventurer.png" alt="プロフィール"/></button></header><div className="content">
{cloud.error&&<div className="notice" role="alert">{cloud.error} <button onClick={()=>cloud.flush().catch(()=>{})}>保存を再試行</button><button onClick={()=>window.location.reload()}>再読み込み</button></div>}{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="お知らせを閉じる">×</button></div>}
{(view==='map'||view==='quests')&&<><div className="page-heading"><div><p className="eyebrow">{view==='map'?'YOUR NEXT ADVENTURE':'QUEST JOURNAL'}</p><h1>{view==='quests'?'きみのクエスト一覧':allClear?'12の世界に、きみの足あと。':'さあ、冒険にでかけよう。'}</h1><p>{cid==='basic'?'12の世界が、きみのひらめきを待っている。':'設計して、試して、改良する。12の開発ミッションに挑もう。'}</p></div><Tabs value={cid} onValueChange={v=>switchCourse(v as CourseId)}><TabsList className="course-tabs" aria-label="コース"><TabsTrigger value="basic">BASIC</TabsTrigger><TabsTrigger value="advance">ADVANCE</TabsTrigger></TabsList></Tabs></div>
{view==='map'?<><section className="map-layout"><div className="map-frame"><div className="map-heading"><span><Compass size={18}/>{cid==='basic'?'はじまりの群島':'クリエイターの航路'}</span><span>{japanCalendar().month}月まで解放 · {chapterCount} / 12 クリア</span></div><div className="world-map"><img className="map-art" src={mapImage} alt="城、研究所、海、魔法学校が道でつながった冒険の島々"/>{places.map(([x,y],i)=>{const clear=cleared(save,cid,i),open=unlocked(save,cid,i);return <button key={i} style={{left:x+'%',top:y+'%'}} className={'map-pin '+(selected===i?'selected ':'')+(clear?'complete':open?'current':'locked')} onClick={()=>setSelected(i)} aria-pressed={selected===i} aria-label={`第${i+1}章 ${course.chapters[i].title} ${clear?'クリアずみ':open?'冒険できる':'未解放'}`}><span>{clear?<Check size={20}/>:open?<Flag size={20}/>:<Lock size={15}/>}</span>{selected===i&&<b>{i+1}. {course.chapters[i].title}</b>}</button>})}<div className="map-caption"><span className="dot"/> 冒険できる場所 <span className="dot muted"/> これからの世界</div></div></div><aside className="quest-preview"><div className="chapter-tag">CHAPTER {String(selected+1).padStart(2,'0')} <span>{ch.month}</span></div><div className="preview-scene"><img src={mapImage} alt="" style={{transformOrigin:crop}}/>{cid==='basic'?<Swords size={30}/>:<Rocket size={30}/>}</div><h2>{ch.title}</h2><p>{ch.world}</p><div className="quest-count"><Flag size={17}/> {ch.missions.length}つのミッション <span>{doneCount} / {ch.missions.length}</span></div><Progress value={doneCount/3*100} aria-label="この章の進みぐあい"/><div className="reward-mini"><Trophy/><div><small>{cleared(save,cid,selected)?'獲得したたからもの':'この世界のたからもの'}</small><strong>{ch.award.name}</strong></div></div><button className="gold-button" disabled={!canOpen||!loaded} onClick={()=>openChapter(selected)}>{!canOpen?'その月になると解放':cleared(save,cid,selected)?'もう一度、冒険する':doneCount?'冒険をつづける':'冒険をはじめる'}{canOpen?<ArrowRight size={18}/>:<Lock size={17}/>}</button><p className="save-note">進みぐあいはアカウントにセーブ</p></aside></section><section className="guide-strip"><img src="/adventurer.png" alt="案内役リオ"/><div><span className="eyebrow">{guide}</span><p>「{allClear?'全章クリア、おめでとう！ 自分の作品に新しい工夫を足してみよう。':chapterCount>0?`つぎは「${course.chapters[current].title}」。新しい出会いが待っているよ。`:cid==='basic'?'最初の目的地は、勇者と魔物の世界。一歩動かすことから、一緒にはじめよう！':'最初の依頼は、壊れたゲームの修理。まずは何が起きているか調べよう。'}」</p></div><Sparkles/></section></>:<div className="quest-grid">{course.chapters.map((c,i)=><button className={'quest-card '+(cleared(save,cid,i)?'cleared':'')} key={i} onClick={()=>openChapter(i)}><span className="eyebrow">CHAPTER {String(i+1).padStart(2,'0')} · {c.month}</span><h2>{c.title}</h2><p>{c.world}</p><span className="quest-card-foot">{cleared(save,cid,i)?<><Check size={17}/> クリアずみ</>:unlocked(save,cid,i)?<><Flag size={17}/> {progress(save,cid,i).missions.filter(Boolean).length} / 3 ミッション</>:<><Lock size={17}/> その月になると解放</>}<ChevronRight size={18}/></span></button>)}</div>}</>}
{view==='studio'&&<Workshop key={cid} cid={cid} teacher={isTeacher}/>}
{view==='chapter'&&<><button className="back-link" onClick={()=>go('map')}><ArrowLeft size={16}/> 冒険マップにもどる</button><Novel key={cid+selected} cid={cid} chapter={selected} onStart={()=>openMission(Math.max(0,cp.missions.findIndex(x=>!x)))}/><ChapterFiles key={cid+selected} cid={cid} chapter={selected} teacher={isTeacher}/>{!isTeacher&&<ChapterSubmit cid={cid} chapter={selected}/>}<div className="section-heading"><h2>この世界のクエスト</h2><span>{doneCount} / 3 クリア</span></div><div className="mission-path">{ch.missions.map((m,i)=><button className={'path-step '+(cp.missions[i]?'done':'')} key={i} onClick={()=>openMission(i)}><span className="path-number">{cp.missions[i]?<Check/>:`0${i+1}`}</span><span><small>MISSION {i+1}</small><strong>{m.title}</strong></span><ChevronRight size={18}/></button>)}</div>{doneCount>0&&<div className="world-result"><Sparkles size={20}/><p>{outcome(cid,selected,Math.max(0,cp.missions.lastIndexOf(true)))}</p></div>}<section className="challenge-panel"><div><span className="eyebrow">BONUS QUEST</span><h2>きみだけの工夫を、もうひとつ。</h2><p>{ch.challenge}</p></div><label className="check-row"><Checkbox checked={cp.challenge} disabled={doneCount!==3} onCheckedChange={value=>setSave(s=>({...s,progress:{...s.progress,[cid]:{...s.progress[cid],[selected]:{...progress(s,cid,selected),challenge:value===true}}}}))}/>{cp.challenge?'チャレンジ達成！':doneCount===3?'チャレンジできた！':'3つクリアすると挑戦できるよ'}</label></section></>}
{view==='mission'&&<><button className="back-link" onClick={()=>go('chapter')}><ArrowLeft size={16}/> {ch.title}</button><div className="mission-layout"><section className="mission-main"><div className="mission-top"><span className="eyebrow">CHAPTER {String(selected+1).padStart(2,'0')} / MISSION {String(mi+1).padStart(2,'0')}</span><span className="xp-chip">{cp.missions[mi]?<Check size={15}/>:<Sparkles size={15}/>} {cp.missions[mi]?'クリアずみ':'+100 EXP'}</span></div><h1>{mission.title}</h1><div className="mission-scene"><img src={mapImage} alt="冒険の舞台" style={{objectPosition:crop}}/><div><Flag/><span>{mi===0?'最初の力を手に入れよう':mi===2?'この世界を完成させよう':'新しい仕組みを作ろう'}</span></div></div><div className="objective"><span className="eyebrow">今回のゴール</span><p>{mission.goal}</p></div><div className="mentor-line"><img src="/adventurer.png" alt="リオ"/><p>{cid==='basic'?'「どのブロックならできそう？ まずは動かして、たしかめてみよう。」':'「最初に、どう動くべきか考えよう。小さく作って、ひとつずつ検証してみて。」'}</p></div><a className="gold-button scratch-link" href={safeUrl(save.opts.scratchUrl)||course.scratchUrl} target="_blank" rel="noopener noreferrer">Scratchで作る<ExternalLink size={17}/></a><p className="save-note">別のタブでScratchが開きます。できたら、ここにもどろう。</p><section className="verify-panel"><h2><Check size={20}/> 動かして、たしかめよう</h2><p>{mission.goal}</p><label className="check-row"><Checkbox checked={checked||cp.missions[mi]} disabled={cp.missions[mi]} onCheckedChange={v=>setChecked(v===true)}/>Scratchで動かして、ゴールの動きをたしかめた</label><p className="micro">作品の自動判定はありません。自分で確認して記録します。</p>{cp.missions[mi]?<div className="completed-actions"><span><Check size={18}/> このミッションはクリアずみ</span><button className="subtle" onClick={()=>setConfirm('undo')}>取り消す</button></div>:<button className="gold-button" disabled={!checked} onClick={complete}>できた！ 冒険をすすめる <ArrowRight size={17}/></button>}</section><div className="mission-pager"><button disabled={mi===0} onClick={()=>openMission(mi-1)}><ArrowLeft size={16}/> 前のミッション</button><button disabled={mi===2} onClick={()=>openMission(mi+1)}>つぎのミッション <ArrowRight size={16}/></button></div></section><aside className="hint-panel"><span className="eyebrow">ADVENTURER'S TOOLKIT</span><h2><Lightbulb size={22}/> ひらめきのヒント</h2><p>困ったら、ひとつずつ。<br/>自分のペースで大丈夫。</p><div className="hint-stack">{mission.hints.slice(0,hints).map((h,i)=><div className="hint-box" key={i}><span>HINT {i+1}</span><p>{h}</p></div>)}</div>{hints<mission.hints.length&&<button className="outline-button" onClick={()=>setHints(v=>v+1)}><Lightbulb size={17}/> ヒント {hints+1} をひらく</button>}{hints===mission.hints.length&&!answer&&!save.opts.hideAnswer&&<button className="outline-button" onClick={()=>setAnswer(true)}>考えかたを見る</button>}{answer&&<div className="hint-box answer"><span>考えかたの一例</span><p>{mission.answer}</p></div>}<div className="toolbox"><h3><BookOpen size={17}/> この章でつかう道具</h3>{ch.learn.map((l,i)=><details key={i}><summary>{l.block}</summary><p>{l.why}</p></details>)}</div></aside></div></>}
{view==='awards'&&<><div className="page-heading"><div><span className="eyebrow">TREASURE COLLECTION</span><h1>冒険の証を、ここに。</h1><p>ひとつずつ増えていく、きみだけのたからもの。</p></div><span className="collection-count"><Trophy size={22}/>{chapterCount} / 12</span></div><div className="awards-grid">{course.chapters.map((c,i)=>{const got=cleared(save,cid,i);return <article className={'award-card '+(got?'earned':'')} key={i}><div className="medallion">{got?<Trophy/>:<Lock/>}</div><span className="eyebrow">CHAPTER {String(i+1).padStart(2,'0')}</span><h2>{c.award.name}</h2><p>{got?c.award.text:`「${c.title}」をクリアして手に入れよう。`}</p>{got&&<span className="earned-label"><Check size={14}/> 獲得ずみ</span>}</article>})}</div><div className="section-heading"><h2>先生からの特別賞</h2><span>{save.special.length}個獲得</span></div><div className="special-grid">{specialAwards.map(a=>{const n=save.special.filter(x=>x.id===a.id).length;return <div className={'special-card '+(n?'earned':'')} key={a.id}><Medal/><strong>{a.name}</strong><span>{n?`${n} 回獲得`:'作品の工夫を先生に見せよう'}</span></div>})}</div></>}
{view==='profile'&&<><div className="page-heading"><div><span className="eyebrow">ADVENTURER PROFILE</span><h1>きみの冒険は、つづいていく。</h1></div></div><div className="profile-panel"><img src="/adventurer.png" alt="きみの冒険者"/><div><label htmlFor="name">冒険者のなまえ</label><input id="name" value={save.name} readOnly aria-label="登録したなまえ"/><h2>Lv. {level} <span>{level>=13?'世界をつなぐクリエイター':level>=5?'ひらめきの冒険者':'はじまりの冒険者'}</span></h2><Progress value={total%3/3*100} aria-label="次のレベルまでの経験値"/><p className="micro">{total*100} EXP · あと{3-total%3}ミッションでレベルアップ</p></div></div><div className="stat-grid">{[[total,'ミッションクリア'],[courses.reduce((n,c)=>n+c.chapters.filter((_,i)=>cleared(save,c.id as CourseId,i)).length,0),'世界をクリア'],[courses.reduce((n,c)=>n+c.chapters.filter((_,i)=>progress(save,c.id as CourseId,i).challenge).length,0),'チャレンジ達成'],[save.special.length,'特別賞']].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div><div className="section-heading"><h2>コースごとの足あと</h2></div><div className="course-records">{courses.map(c=>{const n=c.chapters.filter((_,i)=>cleared(save,c.id as CourseId,i)).length;return <button key={c.id} className="record-course" onClick={()=>switchCourse(c.id as CourseId)}><span className="eyebrow">{c.name}</span><h2>{c.bookTitle}</h2><p>{c.description}</p><Progress value={n/12*100} aria-label={`${c.name}の進捗`}/><span>{n} / 12 章クリア <ArrowRight size={17}/></span></button>})}</div></>}
{view==='settings'&&(isTeacher?<Teacher onSettings={opts=>setSave(s=>({...s,opts}))}/>:<><div className="page-heading"><div><span className="eyebrow">YOUR ADVENTURE RECORD</span><h1>記録の管理</h1><p>記録は「{account.user.name}」のアカウントに保存されます。</p></div></div><section className="settings-panel"><h2>バックアップと引き継ぎ</h2><p>別のパソコンでも、同じ名前とパスワードでログインすると続きを使えます。以前のHTML版の記録もここから読みこめます。</p><div className="settings-buttons"><button className="outline-button" onClick={exportSave}><Download size={18}/>記録を書きだす</button><button className="outline-button" onClick={()=>fileRef.current?.click()}><Upload size={18}/>記録を読みこむ</button><input type="file" hidden ref={fileRef} accept=".json,application/json" onChange={e=>importFile(e.target.files?.[0])}/></div><p className="micro">読み込みでは学習の進みぐあいを引き継ぎます。授業設定と先生からの特別賞は変更されません。</p></section></>)}
</div></main><Dialog open={!!celebration} onOpenChange={open=>{if(!open)setCelebration(null)}}><DialogContent className="celebration"><div className="celebration-spark"><Sparkles/><Star/><Sparkles/></div><span className="eyebrow">{celebration?.chapter?'WORLD CLEAR!':'MISSION CLEAR!'}</span><div className="medallion"><Trophy/></div><DialogTitle>{celebration?.chapter?ch.award.name:'新しい力を手に入れた！'}</DialogTitle><DialogDescription>{celebration?.text}</DialogDescription><div className="experience">+100 EXP <span>Lv. {level}</span></div>{celebration?.chapter&&selected<11&&<p className="unlock-message"><Lock size={15}/> 新しい冒険の証を手に入れた！</p>}<button className="gold-button" onClick={afterCelebration}>{celebration?.chapter?'冒険マップへ':'つぎのクエストへ'}<ArrowRight size={17}/></button></DialogContent></Dialog><AlertDialog open={!!confirm} onOpenChange={v=>{if(!v)setConfirm(null)}}><AlertDialogContent className="confirm-dialog"><AlertDialogTitle>{confirm==='reset'?'すべての記録を消しますか？':confirm==='import'?'この記録に入れ替えますか？':'クリアを取り消しますか？'}</AlertDialogTitle><AlertDialogDescription>{confirm==='reset'?'消した記録は元にもどせません。必要なら先に書きだしてください。':confirm==='import'?`${pendingImport?.name||'冒険者'}の記録（${pendingImport?totalMissions(pendingImport):0}ミッションクリア）に置き換わります。今の記録が必要なら先に書きだしてください。`:'このミッションの経験値と、章のクリア判定が取り消されます。月ごとの解放はそのままです。'}</AlertDialogDescription><div className="confirm-actions"><AlertDialogCancel>やめる</AlertDialogCancel><button className="gold-button" onClick={confirmed}>{confirm==='reset'?'記録を消す':confirm==='import'?'入れ替える':'取り消す'}</button></div></AlertDialogContent></AlertDialog></SidebarProvider>
}
