'use client';
import {useEffect,useRef,useState} from 'react';
import {Archive,BookOpen,Check,Download,Eye,EyeOff,FileArchive,Upload,Send} from 'lucide-react';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Checkbox} from '@/components/ui/checkbox';
import {api} from './accounts';
import {courses,type CourseId} from './game';
import {FileDownload,SubmissionDialog,upload,type FileMeta} from './workshop';
type Resource={id:string;kind:'material'|'answer';visible:boolean;updatedAt:number;file:FileMeta};
function ResourceSlot({kind,current,cid,chapter,onSaved}:{kind:'material'|'answer';current?:Resource;cid:CourseId;chapter:number;onSaved:()=>void}){const [file,setFile]=useState<File|null>(null);const [visible,setVisible]=useState(current?.visible??kind==='material');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const input=useRef<HTMLInputElement>(null);useEffect(()=>{setFile(null);setVisible(current?.visible??kind==='material');setMessage('');if(input.current)input.current.value=''},[cid,chapter,current?.id,current?.file.id]);async function save(){setBusy(true);setMessage('');try{if(file){if(!/\.sb3$/i.test(file.name)||file.size>10*1024*1024)throw Error('10MB以内の.sb3ファイルを選んでください');const form=new FormData();form.set('course',cid);form.set('chapter',String(chapter));form.set('kind',kind);form.set('visible',String(visible));form.set('file',file);await upload('/api/resources',form)}else if(current)await api('/api/resources',{id:current.id,visible},'PATCH');else throw Error('sb3ファイルを選んでください');setMessage('保存しました。');onSaved()}catch(e){setMessage(e instanceof Error?e.message:'保存できませんでした')}finally{setBusy(false)}}return <section className="resource-slot"><div className="resource-slot-title">{kind==='material'?<Archive/>:<BookOpen/>}<div><h2>{kind==='material'?'素材・スターター用 sb3':'答え・完成例用 sb3'}</h2><p>{kind==='material'?'スプライトや背景を入れた、制作の出発点。':'先生が公開した完成例を生徒に配れます。'}</p></div></div>{current?<><FileDownload file={current.file}/><span className={'visibility-tag '+(current.visible?'shown':'')} >{current.visible?<Eye size={15}/>:<EyeOff size={15}/>} {current.visible?'生徒に公開する設定':'先生だけに表示'}</span></>:<div className="resource-missing"><FileArchive size={26}/><p>まだファイルはありません</p></div>}<label className="resource-picker">{file?file.name:current?'新しいsb3に差し替える':'sb3ファイルを選ぶ'}<input ref={input} type="file" accept=".sb3" onChange={e=>setFile(e.target.files?.[0]||null)} disabled={busy}/></label><label className="check-row"><Checkbox checked={visible} onCheckedChange={v=>setVisible(v===true)} disabled={busy}/>生徒に公開する</label>{kind==='answer'&&<p className="micro">授業設定の「考えかたの一例をかくす」が有効な場合、公開にしても生徒には表示されません。</p>}<button className="gold-button" disabled={busy||!file&&!current} onClick={save}><Upload size={16}/>{busy?'保存しています…':file?'アップロードして保存':'公開設定を保存'}</button>{message&&<p className="upload-message" role="status">{message}</p>}<p className="micro">.sb3 / 10MBまで。差し替えると、新しいファイルが配布されます。</p></section>}
export default function ResourceManager(){const [cid,setCid]=useState<CourseId>('basic');const [chapter,setChapter]=useState(0);const [resources,setResources]=useState<Resource[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [revision,setRevision]=useState(0);useEffect(()=>{let active=true;setLoading(true);setError('');api(`/api/resources?course=${cid}&chapter=${chapter}`).then(d=>{if(active)setResources(d.resources)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[cid,chapter,revision]);return <><div className="page-heading"><div><span className="eyebrow">CHAPTER ASSETS</span><h1>章の素材と、完成例。</h1><p>コースと章を選び、Scratchファイルを配布します。</p></div></div><div className="resource-selectors"><label>コース<NativeSelect value={cid} onChange={e=>setCid(e.target.value as CourseId)}><NativeSelectOption value="basic">BASIC</NativeSelectOption><NativeSelectOption value="advance">ADVANCE</NativeSelectOption></NativeSelect></label><label>章<NativeSelect value={chapter} onChange={e=>setChapter(Number(e.target.value))}>{courses[cid==='basic'?0:1].chapters.map((c,i)=><NativeSelectOption key={i} value={i}>{c.month} · 第{i+1}章 {c.title}</NativeSelectOption>)}</NativeSelect></label></div>{error?<div className="notice" role="alert">{error}<button onClick={()=>setRevision(n=>n+1)}>再読み込み</button></div>:loading?<p role="status">章のファイルを読み込み中…</p>:<div className="resource-slots">{(['material','answer'] as const).map(kind=><ResourceSlot key={cid+chapter+kind} cid={cid} chapter={chapter} kind={kind} current={resources.find(r=>r.kind===kind)} onSaved={()=>setRevision(n=>n+1)}/>)}</div>}</>}
export function ChapterFiles({cid,chapter,teacher=false}:{cid:CourseId;chapter:number;teacher?:boolean}){const [resources,setResources]=useState<Resource[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);useEffect(()=>{let active=true;api(`/api/resources?course=${cid}&chapter=${chapter}`).then(d=>{if(active)setResources(d.resources)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[cid,chapter]);return <section className="chapter-files"><h2><Archive size={20}/>この章のScratchファイル</h2>{error?<p role="alert">{error}</p>:loading?<p role="status">ファイルを確認しています…</p>:!resources.length?<p className="micro">{teacher?'先生の部屋の「章のファイル」からアップロードできます。':'先生がファイルを用意すると、ここからダウンロードできます。'}</p>:<><div className="chapter-file-list">{resources.map(r=><div key={r.id}><span>{r.kind==='material'?'素材・スターター':'答え・完成例'}</span><FileDownload file={r.file}/>{teacher&&!r.visible&&<small>先生だけに表示</small>}</div>)}</div><p className="micro">ダウンロード後、Scratchの「ファイル」→「コンピューターから読み込む」で開こう。</p></>}</section>}
export function ChapterSubmit({cid,chapter}:{cid:CourseId;chapter:number}){const [open,setOpen]=useState(false);const [message,setMessage]=useState('');return <section className="chapter-submit"><div><span className="eyebrow">SHOW YOUR CREATION</span><h2>この章で作った作品を、先生に見せよう。</h2><p>提出した作品は「自由制作」の一覧にも残るよ。</p>{message&&<p className="upload-message" role="status">{message}</p>}</div><button className="gold-button" onClick={()=>setOpen(true)}><Send size={17}/>作品を提出する</button><SubmissionDialog cid={cid} chapter={chapter} open={open} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);setMessage('作品を提出しました！ 先生からのコメントを待とう。')}}/></section>}
