import {env} from 'cloudflare:workers';
import {freshSave,parseSave,safeUrl,type Save} from '../app/game';
export function db(){if(!env.DB)throw new Error('保存先の準備ができていません');return env.DB}
export type Identity={role:'teacher'|'student';studentId:string|null;tokenHash:string};
export type Settings=Save['opts'];
export const defaultSettings:Settings={unlockAll:false,hideAnswer:false,scratchUrl:''};
const encoder=new TextEncoder();
const hex=(b:ArrayBuffer|Uint8Array)=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('');
export async function digest(value:string){return hex(await crypto.subtle.digest('SHA-256',encoder.encode(value)))}
export async function hashPassword(password:string,salt=hex(crypto.getRandomValues(new Uint8Array(16)))){const key=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']);return salt+':'+hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:encoder.encode(salt),iterations:100000,hash:'SHA-256'},key,256))}
export async function verifyPassword(password:string,stored:string){if(!/^[a-f0-9]{32}:[a-f0-9]{64}$/.test(stored))return false;const got=await hashPassword(password,stored.split(':')[0]);let diff=got.length^stored.length;for(let i=0;i<got.length;i++)diff|=got.charCodeAt(i)^stored.charCodeAt(i);return diff===0}
export async function teacherPasswordValid(password:string){if(!env.TEACHER_PASSWORD_HASH)throw new Error('先生用ログインの設定がまだ完了していません');return verifyPassword(password,env.TEACHER_PASSWORD_HASH)}
export function response(data:unknown,status=200,headers:Record<string,string>={}){return Response.json(data,{status,headers:{'Cache-Control':'no-store',...headers}})}
export function sameOrigin(request:Request){const origin=request.headers.get('origin');const site=new URL(request.url).origin;if(!origin||origin!==site)throw new Error('この画面を開き直して、もう一度お試しください')}
export async function body(request:Request){sameOrigin(request);if(!request.headers.get('content-type')?.includes('application/json'))throw Error('入力の形式が違います');const raw=await request.text();if(raw.length>150000)throw Error('データが大きすぎます');const value=JSON.parse(raw);if(!value||typeof value!=='object'||Array.isArray(value))throw Error('入力の形式が違います');return value as Record<string,unknown>}
export async function identity(request:Request):Promise<Identity|null>{const token=request.headers.get('cookie')?.match(/(?:^|;\s*)sq_session=([^;]+)/)?.[1];if(!token||!/^[a-f0-9]{64}$/.test(token))return null;const hashed=await digest(token);const row=await db().prepare('SELECT student_id,role FROM sessions WHERE token_hash = ? AND expires_at > ?').bind(hashed,Date.now()).first<{student_id:string|null;role:string}>();return row&&['teacher','student'].includes(row.role)?{role:row.role as Identity['role'],studentId:row.student_id,tokenHash:hashed}:null}
export async function createSession(request:Request,role:Identity['role'],studentId:string|null){const token=hex(crypto.getRandomValues(new Uint8Array(32)));const hash=await digest(token);await db().batch([db().prepare('DELETE FROM sessions WHERE expires_at < ?').bind(Date.now()),db().prepare('INSERT INTO sessions (token_hash,student_id,role,expires_at) VALUES (?,?,?,?)').bind(hash,studentId,role,Date.now()+7*86400000)]);return cookie(request,token,7*86400)}
export function cookie(request:Request,token:string,age:number){return `sq_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${age}${new URL(request.url).protocol==='https:'?'; Secure':''}`}
export async function settings():Promise<Settings>{const row=await db().prepare('SELECT settings_json FROM classroom WHERE id = ?').bind('main').first<{settings_json:string}>();if(!row)return {...defaultSettings};const x=JSON.parse(row.settings_json);return {unlockAll:x.unlockAll===true,hideAnswer:x.hideAnswer===true,scratchUrl:typeof x.scratchUrl==='string'&&safeUrl(x.scratchUrl)?x.scratchUrl:''}}
export async function rateLimit(request:Request,scope:string,limit=20){const ip=request.headers.get('cf-connecting-ip')||'local';const key=await digest(scope+':'+ip);const now=Date.now();const row=await db().prepare('INSERT INTO auth_attempts (key,count,reset_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count = CASE WHEN reset_at < ? THEN 1 ELSE count + 1 END, reset_at = CASE WHEN reset_at < ? THEN ? ELSE reset_at END RETURNING count').bind(key,now+600000,now,now,now+600000).first<{count:number}>();if((row?.count||0)>limit)throw Error('何度も試されたため、10分ほど待ってからお試しください')}
export async function accountData(who:Identity){const opts=await settings();if(who.role==='teacher')return {user:{id:'teacher',name:'先生',role:'teacher'},save:{...freshSave(),name:'先生',opts},revision:0,serverTime:new Date().toISOString()};const row=await db().prepare('SELECT id,name,save_json,revision FROM students WHERE id = ?').bind(who.studentId).first<{id:string;name:string;save_json:string;revision:number}>();if(!row)throw Error('ログインし直してください');return {user:{id:row.id,name:row.name,role:'student'},save:{...parseSave(JSON.parse(row.save_json)),name:row.name,opts},revision:row.revision,serverTime:new Date().toISOString()}}
export function errorResponse(e:unknown,status=400){return response({error:e instanceof Error?e.message:'処理できませんでした'},status)}
