import {env} from 'cloudflare:workers';
import {inflateRawSync} from 'node:zlib';
import {db,sameOrigin} from './auth';
export const MAX_UPLOAD=10*1024*1024;
export type ProjectSummary={sprites:number;blocks:number;costumes:number;names:string[]};
export function bucket(){if(!env.FILES)throw Error('ファイル保存先の準備ができていません');return env.FILES}
export function scratchProjectUrl(raw:unknown){if(raw===''||raw===undefined||raw===null)return '';if(typeof raw!=='string')throw Error('作品URLを確認してください');try{const u=new URL(raw.trim());const m=u.pathname.match(/^\/projects\/(\d+)\/?$/);if(u.protocol!=='https:'||u.hostname!=='scratch.mit.edu'||u.username||u.password||!m)throw Error();return `https://scratch.mit.edu/projects/${m[1]}/`}catch{throw Error('共有したScratch作品のURLを入力してください（https://scratch.mit.edu/projects/数字/）')}}
export async function uploadForm(request:Request){sameOrigin(request);if(!request.headers.get('content-type')?.startsWith('multipart/form-data;'))throw Error('ファイルを選んでください');const length=Number(request.headers.get('content-length')||0);if(length>MAX_UPLOAD+65536)throw Error('ファイルは10MB以内にしてください');const reader=request.body?.getReader();if(!reader)throw Error('ファイルを読みこめません');let size=0;const parts:Uint8Array[]=[];while(true){const {value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>MAX_UPLOAD+65536){await reader.cancel();throw Error('ファイルは10MB以内にしてください')}parts.push(value)}const buffer=new Uint8Array(size);let offset=0;for(const p of parts){buffer.set(p,offset);offset+=p.byteLength}return new Response(buffer,{headers:{'Content-Type':request.headers.get('content-type')!}}).formData()}
export function inspectSb3(bytes:Uint8Array):ProjectSummary{if(bytes.byteLength<22||bytes.byteLength>MAX_UPLOAD)throw Error('有効な10MB以内のsb3ファイルを選んでください');const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let e=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(v.getUint32(i,true)===0x06054b50&&i+22+v.getUint16(i+20,true)===bytes.length){e=i;break}if(e<0)throw Error('Scratchから保存したsb3ファイルを選んでください');const entries=v.getUint16(e+10,true),directory=v.getUint32(e+16,true);if(v.getUint16(e+4,true)||v.getUint16(e+6,true)||entries<1||entries>10000||directory+v.getUint32(e+12,true)!==e)throw Error('このsb3ファイルの形式は対応していません');let offset=directory;let manifest:Uint8Array|null=null;for(let i=0;i<entries;i++){if(offset+46>e||v.getUint32(offset,true)!==0x02014b50)throw Error('ファイルが壊れています');const flags=v.getUint16(offset+8,true),method=v.getUint16(offset+10,true),compressed=v.getUint32(offset+20,true),expanded=v.getUint32(offset+24,true),nl=v.getUint16(offset+28,true),el=v.getUint16(offset+30,true),cl=v.getUint16(offset+32,true),lo=v.getUint32(offset+42,true);if(offset+46+nl+el+cl>e)throw Error('ファイルが壊れています');const name=new TextDecoder().decode(bytes.subarray(offset+46,offset+46+nl));if(name==='project.json'){if(manifest||expanded>2*1024*1024||flags&1||![0,8].includes(method)||lo+30>directory||v.getUint32(lo,true)!==0x04034b50)throw Error('作品データを読みこめません');const start=lo+30+v.getUint16(lo+26,true)+v.getUint16(lo+28,true);if(start+compressed>directory)throw Error('作品データが壊れています');try{manifest=method===0?bytes.subarray(start,start+compressed):inflateRawSync(bytes.subarray(start,start+compressed),{maxOutputLength:2*1024*1024});if(manifest.length!==expanded)throw Error()}catch{throw Error('作品データを読みこめません')}}offset+=46+nl+el+cl}if(!manifest||offset!==e)throw Error('Scratch作品のproject.jsonが見つかりません');let project;try{project=JSON.parse(new TextDecoder().decode(manifest))}catch{throw Error('Scratch作品のデータが壊れています')}if(!Array.isArray(project.targets)||project.targets.length<1||project.targets.length>1000||!project.targets.some((t:any)=>t?.isStage===true))throw Error('Scratch 3の作品を選んでください');let blocks=0,costumes=0;const names:string[]=[];for(const t of project.targets){if(!t||typeof t!=='object')throw Error('作品データが正しくありません');if(t.isStage!==true)names.push(String(t.name||'スプライト').slice(0,80));if(t.blocks&&typeof t.blocks==='object')blocks+=Object.keys(t.blocks).length;if(Array.isArray(t.costumes))costumes+=t.costumes.length}return {sprites:names.length,blocks,costumes,names:names.slice(0,30)}}
export type StoredFile={id:string;originalName:string;size:number;summary:ProjectSummary};
export async function storeFile(file:File):Promise<StoredFile>{if(!/\.sb3$/i.test(file.name)||file.size>MAX_UPLOAD||!file.size)throw Error('10MB以内の.sb3ファイルを選んでください');const bytes=new Uint8Array(await file.arrayBuffer());const summary=inspectSb3(bytes);const id=crypto.randomUUID(),key=`scratch/${id}.sb3`,name=file.name.replace(/[\x00-\x1f\x7f/\\]/g,'_').slice(0,160);await bucket().put(key,bytes,{httpMetadata:{contentType:'application/octet-stream'}});try{await db().prepare('INSERT INTO stored_files (id,object_key,original_name,size,summary_json,created_at) VALUES (?,?,?,?,?,?)').bind(id,key,name,bytes.length,JSON.stringify(summary),Date.now()).run()}catch(e){await bucket().delete(key);throw e}return {id,originalName:name,size:bytes.length,summary}}
export async function discardFile(id:string){const usage=await db().prepare('SELECT id FROM submissions WHERE file_id = ? UNION ALL SELECT id FROM chapter_resources WHERE file_id = ? LIMIT 1').bind(id,id).first();if(usage)return;const row=await db().prepare('SELECT object_key FROM stored_files WHERE id = ?').bind(id).first<{object_key:string}>();if(!row)return;await bucket().delete(row.object_key);await db().prepare('DELETE FROM stored_files WHERE id = ?').bind(id).run()}
export function formText(form:FormData,key:string,max:number,required=false){const value=form.get(key);if(value!==null&&typeof value!=='string')throw Error('入力の形式が違います');const text=(value||'').trim();if(text.length>max||required&&!text)throw Error(`${key==='title'?'作品のタイトル':'説明'}を${max}文字以内で入力してください`);return text}
export function courseChapter(course:unknown,chapter:unknown,optional=false){if(!['basic','advance'].includes(String(course)))throw Error('コースを選んでください');if(optional&&(chapter===''||chapter===null||chapter===undefined))return {course:String(course),chapter:null};if(chapter===null||chapter===undefined||chapter==='')throw Error('章を選んでください');const ci=Number(chapter);if(!Number.isInteger(ci)||ci<0||ci>11)throw Error('章を選んでください');return {course:String(course),chapter:ci}}
