import assert from 'node:assert/strict';
import {zipSync,strToU8} from 'fflate';
const origin='http://localhost:3000';
function client(){let cookie='';return async(path,data,method='POST',csrf=true)=>{const multipart=data instanceof FormData;const r=await fetch(origin+path,{method:data===undefined?'GET':method,headers:{...(cookie?{Cookie:cookie}:{}),...(data!==undefined&&csrf?{Origin:origin}:{}),...(data!==undefined&&!multipart?{'Content-Type':'application/json'}:{})},body:data===undefined?undefined:multipart?data:JSON.stringify(data)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];if(path.startsWith('/api/files/')&&r.ok)return {status:r.status,bytes:new Uint8Array(await r.arrayBuffer()),headers:r.headers};const raw=await r.text();let parsed;try{parsed=JSON.parse(raw)}catch{parsed={error:raw}}return {status:r.status,data:parsed}}}
const bytes=zipSync({'project.json':strToU8(JSON.stringify({targets:[{isStage:true,name:'Stage',blocks:{},costumes:[]},{isStage:false,name:'Cat',blocks:{a:{}},costumes:[]}]}))});
function form(values={},file=bytes,name='作品.sb3'){const f=new FormData();for(const [k,v] of Object.entries({course:'basic',chapter:'',title:'自由な冒険',description:'自分で作りました',...values}))f.set(k,String(v));if(file)f.set('file',new Blob([file]),name);return f}
const a=client(),b=client(),t=client(),guest=client(),suffix=Date.now();for(const [c,n] of [[a,'作品A'],[b,'作品B']])assert.equal((await c('/api/account',{action:'register',name:n+suffix,password:'test-password-123'})).status,200);
assert.equal((await t('/api/account',{action:'teacher',password:process.env.TEST_TEACHER_PASSWORD})).status,200);
const large=zipSync({'project.json':strToU8(JSON.stringify({targets:[{isStage:true,blocks:{},costumes:[]}]})),'asset.wav':new Uint8Array(9*1024*1024)},{level:0});assert.equal((await a('/api/submissions',form({title:'大きい作品'},large))).status,200);
let r=await a('/api/submissions',form());assert.equal(r.status,200,JSON.stringify(r));const id=r.data.id;
let work=(await a('/api/submissions')).data.submissions.find(s=>s.id===id);assert.equal(work.file.summary.blocks,1);assert.equal((await b('/api/submissions')).data.submissions.length,0);assert.ok((await t('/api/submissions')).data.submissions.some(s=>s.id===id));
let download=await a('/api/files/'+work.file.id);assert.equal(download.status,200);assert.deepEqual(download.bytes,bytes);assert.equal(download.headers.get('x-content-type-options'),'nosniff');assert.equal((await b('/api/files/'+work.file.id)).status,403);assert.equal((await guest('/api/files/'+work.file.id)).status,401);assert.equal((await b('/api/submissions',form({id,revision:0}))).status,404);
assert.equal((await t('/api/submissions',{id,revision:0,feedback:'工夫がいいね！',reviewed:true},'PATCH')).status,200);assert.equal((await a('/api/submissions',form({id,revision:0}))).status,409);assert.equal((await a('/api/submissions')).data.submissions.find(s=>s.id===id).feedback,'工夫がいいね！');
assert.equal((await a('/api/submissions',form({id,revision:1,title:'改良しました'},null))).status,200);work=(await a('/api/submissions')).data.submissions.find(s=>s.id===id);assert.equal(work.reviewed,false);assert.ok(work.file);
assert.equal((await a('/api/submissions',form({},strToU8('bad')))).status,400);assert.equal((await a('/api/submissions',form({},bytes,'bad.zip'))).status,400);assert.equal((await a('/api/submissions',form({projectUrl:'https://example.com'},null))).status,400);assert.equal((await a('/api/submissions',form({projectUrl:'https://scratch.mit.edu/projects/123456789/'},null))).status,200);assert.equal((await a('/api/submissions',form(),'POST',false)).status,400);
assert.equal((await a('/api/resources',form({chapter:0,kind:'material'}))).status,403);
assert.equal((await t('/api/resources',form({chapter:0,kind:'material',visible:true}))).status,200);assert.equal((await t('/api/resources',form({chapter:0,kind:'answer',visible:false}))).status,200);
let resources=(await t('/api/resources?course=basic&chapter=0')).data.resources;const answer=resources.find(r=>r.kind==='answer');assert.equal((await a('/api/resources?course=basic&chapter=0')).data.resources.length,1);assert.equal((await a('/api/files/'+answer.file.id)).status,403);
assert.equal((await t('/api/resources',{id:answer.id,visible:true},'PATCH')).status,200);assert.equal((await a('/api/files/'+answer.file.id)).status,200);
const opts=(await t('/api/teacher')).data.settings;assert.equal((await t('/api/teacher',{action:'settings',settings:{...opts,hideAnswer:true}})).status,200);assert.equal((await a('/api/files/'+answer.file.id)).status,403);assert.equal((await a('/api/resources?course=basic&chapter=0')).data.resources.length,1);assert.equal((await t('/api/teacher',{action:'settings',settings:opts})).status,200);
const old=resources.find(r=>r.kind==='material').file.id;assert.equal((await t('/api/resources',form({chapter:0,kind:'material',visible:true}))).status,200);assert.notEqual((await a('/api/files/'+old)).status,200);
assert.equal((await t('/api/resources',form({chapter:11,kind:'material',visible:true}))).status,200);assert.equal((await a('/api/resources?course=basic&chapter=11')).data.resources.length,0);assert.equal((await a('/api/submissions',form({chapter:11}))).status,400);
assert.equal((await t('/api/resources?course=basic')).status,400);
assert.ok([400,413].includes((await a('/api/submissions',form({},new Uint8Array(10*1024*1024+1)))).status));
for(const c of [a,b,t])await c('/api/account',{action:'logout'});
console.log('PASS: sb3 upload/download, URL submissions, teacher feedback, ownership, revision conflicts, invalid files, CSRF, resource replacement, answer visibility, future chapter locks, 10MB limit.');
